image: gradle:jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  AXELOR_SOURCES_DIR: "~/axelor-sources"

stages:
  - build_and_deploy
  - start

build_and_deploy_local-axelor: &build_and_deploy_docker
  stage: build_and_deploy
  environment:
    name: local-axelor
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .gradle/wrapper
      - .gradle/caches
  before_script:
    - mkdir -p $AXELOR_SOURCES_DIR
  script:
    - git clone https://github.com/axelor/open-suite-webapp.git $AXELOR_SOURCES_DIR
    - sed -e 's|git@github.com:|https://github.com/|' -i $AXELOR_SOURCES_DIR/.gitmodules
    - git checkout master
    - git submodule sync
    - git submodule init
    - git submodule update
    - git submodule foreach git checkout master
    - git submodule foreach git pull origin master
    - echo "the project directory is - $CI_PROJECT_DIR"
    - echo "the absolute path is - $PWD"
    - cp $PWD $AXELOR_SOURCES_DIR/modules/axelor-open-suite
    - $AXELOR_SOURCES_DIR/gradlew clean build -xtest
    - ls -l $AXELOR_SOURCES_DIR/build/libs
  when: manual
  only:
    - master
  tags:
    - axelor


